from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from models.database import get_db, Transcription, Booking
from services.openai_service import OpenAIService
from services.google_calendar import GoogleCalendarService
from datetime import datetime

router = APIRouter()
openai_service = OpenAIService()
calendar_service = GoogleCalendarService()

@router.post("/detect/{transcription_id}")
async def detect_booking(
    transcription_id: int,
        db: Session = Depends(get_db)
        ):
            """
                Detect booking intent from transcription using AI
                    This matches your "Booking Clue Detection" screen
                        """
                            transcription = db.query(Transcription).filter(
                                    Transcription.id == transcription_id
                                        ).first()
                                            
                                                if not transcription:
                                                        raise HTTPException(status_code=404, detail="Transcription not found")
                                                            
                                                                try:
                                                                        # Use OpenAI to detect booking intent and extract details
                                                                                booking_data = await openai_service.detect_booking_intent(transcription.text)
                                                                                        
                                                                                                if booking_data['intent_detected']:
                                                                                                            # Create booking
                                                                                                                        booking = Booking(
                                                                                                                                        transcription_id=transcription.id,
                                                                                                                                                        customer_name=booking_data['customer_name'],
                                                                                                                                                                        customer_phone=booking_data['phone'],
                                                                                                                                                                                        booking_date=booking_data['date'],
                                                                                                                                                                                                        service_type=booking_data['service'],
                                                                                                                                                                                                                        status="detected",
                                                                                                                                                                                                                                        confidence_score=booking_data['confidence']
                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                db.add(booking)
                                                                                                                                                                                                                                                                            db.commit()
                                                                                                                                                                                                                                                                                        db.refresh(booking)
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                "success": True,
                                                                                                                                                                                                                                                                                                                                                "booking_detected": True,
                                                                                                                                                                                                                                                                                                                                                                "confidence": booking_data['confidence'],
                                                                                                                                                                                                                                                                                                                                                                                "booking_id": booking.id,
                                                                                                                                                                                                                                                                                                                                                                                                "details": {
                                                                                                                                                                                                                                                                                                                                                                                                                    "customer_name": booking.customer_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                        "date": booking.booking_date.isoformat(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            "service": booking.service_type
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "signals": booking_data['detected_signals']  # Like in your UI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "success": True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "booking_detected": False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "confidence": booking_data['confidence']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise HTTPException(status_code=500, detail=str(e))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @router.post("/{booking_id}/confirm")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async def confirm_booking(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    booking_id: int,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db: Session = Depends(get_db)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Confirm booking and create calendar event
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        booking = db.query(Booking).filter(Booking.id == booking_id).first()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not booking:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise HTTPException(status_code=404, detail="Booking not found")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Create Google Calendar event
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                event = await calendar_service.create_event(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            customer_name=booking.customer_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        service_type=booking.service_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    booking_date=booking.booking_date
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Update booking status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    booking.status = "confirmed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "success": True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "calendar_link": event['htmlLink'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "event_id": event['id']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=500, detail=str(e))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @router.get("/upcoming")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def get_upcoming_bookings(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db: Session = Depends(get_db)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Get upcoming bookings (for calendar view in your UI)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bookings = db.query(Booking).filter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Booking.booking_date >= datetime.utcnow(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Booking.status == "confirmed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).order_by(Booking.booking_date).all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "bookings": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "id": b.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "customer_name": b.customer_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "customer_phone": b.customer_phone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "booking_date": b.booking_date.isoformat(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "service_type": b.service_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "confidence": b.confidence_score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for b in bookings
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }