from fastapi import APIRouter, Depends, HTTPException, File, UploadFile
from sqlalchemy.orm import Session
from models.database import get_db, Recording
from services.twilio_service import TwilioService
from datetime import datetime
import os

router = APIRouter()
twilio_service = TwilioService()

@router.post("/start")
async def start_recording(
    phone_number: str,
        db: Session = Depends(get_db)
        ):
            """
                Start a new call recording
                    """
                        try:
                                # Initiate call via Twilio
                                        call = twilio_service.start_recording(phone_number)
                                                
                                                        # Save to database
                                                                recording = Recording(
                                                                            call_sid=call.sid,
                                                                                        status="recording",
                                                                                                    start_time=datetime.utcnow()
                                                                                                            )
                                                                                                                    db.add(recording)
                                                                                                                            db.commit()
                                                                                                                                    db.refresh(recording)
                                                                                                                                            
                                                                                                                                                    return {
                                                                                                                                                                "success": True,
                                                                                                                                                                            "call_sid": call.sid,
                                                                                                                                                                                        "recording_id": recording.id,
                                                                                                                                                                                                    "status": "Recording started"
                                                                                                                                                                                                            }
                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                        raise HTTPException(status_code=500, detail=str(e))

                                                                                                                                                                                                                        @router.get("/recent")
                                                                                                                                                                                                                        async def get_recent_recordings(
                                                                                                                                                                                                                            limit: int = 10,
                                                                                                                                                                                                                                db: Session = Depends(get_db)
                                                                                                                                                                                                                                ):
                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                        Get recent call recordings (for the dashboard view)
                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                recordings = db.query(Recording).order_by(
                                                                                                                                                                                                                                                        Recording.created_at.desc()
                                                                                                                                                                                                                                                            ).limit(limit).all()
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                            "recordings": [
                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                        "id": r.id,
                                                                                                                                                                                                                                                                                                                        "call_sid": r.call_sid,
                                                                                                                                                                                                                                                                                                                                        "status": r.status,
                                                                                                                                                                                                                                                                                                                                                        "start_time": r.start_time.isoformat() if r.start_time else None,
                                                                                                                                                                                                                                                                                                                                                                        "duration": str(r.end_time - r.start_time) if r.end_time else "In progress",
                                                                                                                                                                                                                                                                                                                                                                                        "has_transcription": r.transcription is not None,
                                                                                                                                                                                                                                                                                                                                                                                                        "has_booking": r.transcription.booking if r.transcription else None
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                for r in recordings
                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                            @router.get("/{recording_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                            async def get_recording(
                                                                                                                                                                                                                                                                                                                                                                                                                                                recording_id: int,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    db: Session = Depends(get_db)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ):
                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Get specific recording details
                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    recording = db.query(Recording).filter(Recording.id == recording_id).first()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not recording:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=404, detail="Recording not found")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "id": recording.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "call_sid": recording.call_sid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "audio_path": recording.audio_path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "status": recording.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "start_time": recording.start_time.isoformat() if recording.start_time else None,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "end_time": recording.end_time.isoformat() if recording.end_time else None,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "transcription": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "text": recording.transcription.text if recording.transcription else None,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "confidence": recording.transcription.confidence if recording.transcription else None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } if recording.transcription else None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }