from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from models.database import get_db, Recording, Transcription
from services.openai_service import OpenAIService
from datetime import datetime

router = APIRouter()
openai_service = OpenAIService()

@router.post("/{recording_id}")
async def transcribe_recording(
    recording_id: int,
        db: Session = Depends(get_db)
        ):
            """
                Transcribe a recorded call using OpenAI Whisper
                    """
                        # Get recording
                            recording = db.query(Recording).filter(Recording.id == recording_id).first()
                                
                                    if not recording:
                                            raise HTTPException(status_code=404, detail="Recording not found")
                                                
                                                    if not recording.audio_path:
                                                            raise HTTPException(status_code=400, detail="No audio file available")
                                                                
                                                                    try:
                                                                            # Transcribe using OpenAI
                                                                                    result = await openai_service.transcribe_audio(recording.audio_path)
                                                                                            
                                                                                                    # Save transcription
                                                                                                            transcription = Transcription(
                                                                                                                        recording_id=recording.id,
                                                                                                                                    text=result['text'],
                                                                                                                                                confidence=result['confidence'],
                                                                                                                                                            status="completed"
                                                                                                                                                                    )
                                                                                                                                                                            db.add(transcription)
                                                                                                                                                                                    db.commit()
                                                                                                                                                                                            db.refresh(transcription)
                                                                                                                                                                                                    
                                                                                                                                                                                                            return {
                                                                                                                                                                                                                        "success": True,
                                                                                                                                                                                                                                    "transcription_id": transcription.id,
                                                                                                                                                                                                                                                "text": transcription.text,
                                                                                                                                                                                                                                                            "confidence": transcription.confidence
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                # Save failed transcription
                                                                                                                                                                                                                                                                                        transcription = Transcription(
                                                                                                                                                                                                                                                                                                    recording_id=recording.id,
                                                                                                                                                                                                                                                                                                                text="",
                                                                                                                                                                                                                                                                                                                            confidence=0.0,
                                                                                                                                                                                                                                                                                                                                        status="failed"
                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                        db.add(transcription)
                                                                                                                                                                                                                                                                                                                                                                db.commit()
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                raise HTTPException(status_code=500, detail=str(e))

                                                                                                                                                                                                                                                                                                                                                                                @router.get("/{transcription_id}")
                                                                                                                                                                                                                                                                                                                                                                                async def get_transcription(
                                                                                                                                                                                                                                                                                                                                                                                    transcription_id: int,
                                                                                                                                                                                                                                                                                                                                                                                        db: Session = Depends(get_db)
                                                                                                                                                                                                                                                                                                                                                                                        ):
                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                Get transcription details with keyword highlighting
                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                        transcription = db.query(Transcription).filter(
                                                                                                                                                                                                                                                                                                                                                                                                                Transcription.id == transcription_id
                                                                                                                                                                                                                                                                                                                                                                                                                    ).first()
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                            if not transcription:
                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=404, detail="Transcription not found")
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            # Detect keywords (like in your UI design)
                                                                                                                                                                                                                                                                                                                                                                                                                                                keywords = openai_service.detect_keywords(transcription.text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "id": transcription.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "text": transcription.text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "confidence": transcription.confidence,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "status": transcription.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "keywords": keywords,  # ['booking', 'schedule', 'consultation', etc.]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "created_at": transcription.created_at.isoformat()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }