from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from models.database import get_db, Booking, WhatsAppMessage, CalendarEvent
from services.whatsapp_service import WhatsAppService
from datetime import datetime

router = APIRouter()
whatsapp_service = WhatsAppService()

@router.post("/send-confirmation/{booking_id}")
async def send_confirmation(
    booking_id: int,
        db: Session = Depends(get_db)
        ):
            """
                Send WhatsApp confirmation message after booking is created
                    Matches your "WhatsApp Messaging" screen design
                        """
                            booking = db.query(Booking).filter(Booking.id == booking_id).first()
                                
                                    if not booking:
                                            raise HTTPException(status_code=404, detail="Booking not found")
                                                
                                                    # Get calendar event
                                                        calendar_event = db.query(CalendarEvent).filter(
                                                                CalendarEvent.booking_id == booking_id
                                                                    ).first()
                                                                        
                                                                            try:
                                                                                    # Send WhatsApp message
                                                                                            message = await whatsapp_service.send_confirmation(
                                                                                                        to_number=booking.customer_phone,
                                                                                                                    customer_name=booking.customer_name,
                                                                                                                                booking_date=booking.booking_date,
                                                                                                                                            service_type=booking.service_type,
                                                                                                                                                        calendar_link=calendar_event.calendar_link if calendar_event else None
                                                                                                                                                                )
                                                                                                                                                                        
                                                                                                                                                                                # Save message record
                                                                                                                                                                                        whatsapp_msg = WhatsAppMessage(
                                                                                                                                                                                                    booking_id=booking.id,
                                                                                                                                                                                                                message_sid=message.sid,
                                                                                                                                                                                                                            template_type="confirmation",
                                                                                                                                                                                                                                        status="sent"
                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                        db.add(whatsapp_msg)
                                                                                                                                                                                                                                                                db.commit()
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                            "success": True,
                                                                                                                                                                                                                                                                                                        "message_sid": message.sid,
                                                                                                                                                                                                                                                                                                                    "status": "sent",
                                                                                                                                                                                                                                                                                                                                "preview": whatsapp_service.get_confirmation_preview(
                                                                                                                                                                                                                                                                                                                                                booking.customer_name,
                                                                                                                                                                                                                                                                                                                                                                booking.booking_date,
                                                                                                                                                                                                                                                                                                                                                                                booking.service_type,
                                                                                                                                                                                                                                                                                                                                                                                                calendar_event.calendar_link if calendar_event else None
                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                raise HTTPException(status_code=500, detail=str(e))

                                                                                                                                                                                                                                                                                                                                                                                                                                @router.get("/preview/{template_type}")
                                                                                                                                                                                                                                                                                                                                                                                                                                async def get_message_preview(
                                                                                                                                                                                                                                                                                                                                                                                                                                    template_type: str,
                                                                                                                                                                                                                                                                                                                                                                                                                                        customer_name: str = "Sarah Johnson",
                                                                                                                                                                                                                                                                                                                                                                                                                                            booking_date: str = "Wednesday, January 17 at 2:30 PM"
                                                                                                                                                                                                                                                                                                                                                                                                                                            ):
                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Get message template preview (for your UI design)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        template_type: confirmation, 24h_reminder, 2h_reminder
                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                previews = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "confirmation": f"""Hi {customer_name}! 👋

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Your consultation has been confirmed for {booking_date}.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        📅 Add to calendar: https://cal.link/abc123
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        📋 View our catalogue: https://catalogue.example.com

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Looking forward to meeting you!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Best regards,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        The Team""",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "24h_reminder": f"""Hi {customer_name}! 👋

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Reminder: You have an appointment tomorrow at {{{{time}}}}.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        📅 {{{{date}}}} at {{{{time}}}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        📍 {{{{location}}}}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Click here to confirm your attendance""",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "2h_reminder": f"""Your appointment is in 2 hours!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Today at {{{{time}}}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {{{{location}}}}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Click here to confirm your attendance"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "template_type": template_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "preview": previews.get(template_type, "Template not found")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @router.get("/templates")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def get_message_templates():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Get all available WhatsApp message templates
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "templates": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "type": "confirmation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "name": "Booking Confirmation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "description": "Sent immediately after booking is confirmed",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "fields": ["customer_name", "date", "time", "calendar_link", "catalogue_link"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "type": "24h_reminder",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "name": "24-Hour Reminder",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "description": "Sent 24 hours before appointment",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "fields": ["customer_name", "date", "time", "location"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "type": "2h_reminder",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "name": "2-Hour Final Reminder",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "description": "Sent 2 hours before appointment",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "fields": ["customer_name", "time", "location"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @router.get("/messages/{booking_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def get_booking_messages(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        booking_id: int,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db: Session = Depends(get_db)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Get all WhatsApp messages sent for a booking
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        For the "Recent Messages" view in your UI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                messages = db.query(WhatsAppMessage).filter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        WhatsAppMessage.booking_id == booking_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).order_by(WhatsAppMessage.sent_at.desc()).all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "messages": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "id": msg.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "template_type": msg.template_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "status": msg.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "sent_at": msg.sent_at.isoformat(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "message_sid": msg.message_sid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for msg in messages
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }