from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
from datetime import datetime

app = FastAPI(title="Business Dashboard API")

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============ MODELS ============
class TeamMember(BaseModel):
    id: int
    name: str
    avatar_color: str


class Project(BaseModel):
    id: int
    title: str
    status: str  # "On Track", "At Risk", "Delayed", "Completed"
    priority: str  # "HIGH", "MEDIUM", "LOW"
    start_time: str
    end_time: str
    date: str  # "Today", "Tomorrow", or actual date
    team: List[TeamMember]


class OperationsData(BaseModel):
    total_projects: int
    on_track: int
    at_risk: int
    delayed: int
    projects_today: List[Project]
    projects_upcoming: List[Project]
    projects_completed: List[Project]


class DashboardSummary(BaseModel):
    performance: int
    active_projects: int
    username: str


# ============ ENDPOINTS ============


@app.get("/")
def read_root():
    return {"message": "Business Dashboard API", "status": "operational"}


@app.get("/api/operations", response_model=OperationsData)
def get_operations():
    # Sample data
    return {
        "total_projects": 12,
        "on_track": 8,
        "at_risk": 2,
        "delayed": 2,
        "projects_today": [
            {
                "id": 1,
                "title": "Villa Park Residence",
                "status": "On Track",
                "priority": "HIGH",
                "start_time": "9:00 AM",
                "end_time": "2:00 PM",
                "date": "Today",
                "team": [
                    {"id": 1, "name": "John", "avatar_color": "#5B7FFF"},
                    {"id": 2, "name": "Sarah", "avatar_color": "#00D9A5"},
                ],
            },
            {
                "id": 2,
                "title": "Sunset Apartments",
                "status": "At Risk",
                "priority": "MEDIUM",
                "start_time": "10:30 AM",
                "end_time": "4:30 PM",
                "date": "Today",
                "team": [
                    {"id": 3, "name": "Mike", "avatar_color": "#FF6B6B"},
                    {"id": 4, "name": "Emma", "avatar_color": "#FFA500"},
                ],
            },
        ],
        "projects_upcoming": [
            {
                "id": 3,
                "title": "Oakwood Heights",
                "status": "On Track",
                "priority": "LOW",
                "start_time": "10:00 AM",
                "end_time": "3:00 PM",
                "date": "Tomorrow",
                "team": [
                    {"id": 5, "name": "Alex", "avatar_color": "#9B59B6"},
                    {"id": 6, "name": "Lisa", "avatar_color": "#3498DB"},
                ],
            },
            {
                "id": 4,
                "title": "Riverside Complex",
                "status": "Delayed",
                "priority": "HIGH",
                "start_time": "1:00 PM",
                "end_time": "6:00 PM",
                "date": "Tomorrow",
                "team": [
                    {"id": 7, "name": "Chris", "avatar_color": "#E74C3C"},
                ],
            },
        ],
        "projects_completed": [
            {
                "id": 5,
                "title": "Marina Bay Condos",
                "status": "Completed",
                "priority": "MEDIUM",
                "start_time": "9:00 AM",
                "end_time": "2:00 PM",
                "date": "Feb 12",
                "team": [
                    {"id": 8, "name": "David", "avatar_color": "#1ABC9C"},
                    {"id": 9, "name": "Rachel", "avatar_color": "#F39C12"},
                ],
            }
        ],
    }


@app.get("/api/dashboard/summary", response_model=DashboardSummary)
def get_dashboard_summary():
    return {"performance": 85, "active_projects": 12, "username": "Darmiyaan"}


@app.get("/api/health")
def health_check():
    return {"status": "healthy", "timestamp": datetime.now().isoformat()}


from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
from datetime import datetime
# After engine is defined — in main.py or app.py
from model.database import Base, engine
Base.metadata.create_all(bind=engine)

app = FastAPI(title="Business Dashboard API")

# CORS middleware
app.add_middleware(
    CORSMiddleware,
        allow_origins=["http://localhost:3000", "http://localhost:5173"],
            allow_credentials=True,
                allow_methods=["*"],
                    allow_headers=["*"],
                    )
                    # ============ NEW MODELS FOR TEMPLATES ============

                    class Template(BaseModel):
                        id: int
                            title: str
                                category: str
                                    description: str
                                        icon: str
                                            color: str

                                            class TemplatesData(BaseModel):
                                                templates: List[Template]
                                                    categories: List[str]
                                                    # ============ NEW TEMPLATES ENDPOINT ============

                                                    @app.get("/api/templates", response_model=TemplatesData)
                                                    def get_templates():
                                                        return {
                                                                "categories": ["All", "Salon & Beauty", "Home Services", "Retail", "Healthcare", "Restaurants", "Professional"],
                                                                        "templates": [
                                                                                    {
                                                                                                    "id": 1,
                                                                                                                    "title": "Customer Onboarding",
                                                                                                                                    "category": "Salon & Beauty",
                                                                                                                                                    "description": "Automate client intake forms and",
                                                                                                                                                                    "icon": "📅",
                                                                                                                                                                                    "color": "#FFB6C1"
                                                                                                                                                                                                },
                                                                                                                                                                                                            {
                                                                                                                                                                                                                            "id": 2,
                                                                                                                                                                                                                                            "title": "Service Scheduling",
                                                                                                                                                                                                                                                            "category": "Home Services",
                                                                                                                                                                                                                                                                            "description": "Streamline booking and service",
                                                                                                                                                                                                                                                                                            "icon": "🏠",
                                                                                                                                                                                                                                                                                                            "color": "#87CEEB"
                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                    "id": 3,
                                                                                                                                                                                                                                                                                                                                                                    "title": "Inventory Management",
                                                                                                                                                                                                                                                                                                                                                                                    "category": "Retail",
                                                                                                                                                                                                                                                                                                                                                                                                    "description": "Track stock levels and automate",
                                                                                                                                                                                                                                                                                                                                                                                                                    "icon": "🛒",
                                                                                                                                                                                                                                                                                                                                                                                                                                    "color": "#DDA0DD"
                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "id": 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "title": "Patient Follow-up",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "category": "Healthcare",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "description": "Automated patient communication and",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "icon": "🏥",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "color": "#90EE90"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "id": 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "title": "Order Processing",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "category": "Restaurants",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "description": "Streamline order management and",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "icon": "🍽️",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "color": "#FFE4B5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "id": 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "title": "Client Management",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "category": "Professional",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "description": "Organize client information and",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "icon": "💼",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "color": "#E6E6FA"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.get("/api/health")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def health_check():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {"status": "healthy", "timestamp": datetime.now().isoformat()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # In backend/main.py — add at the bottom

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from pydantic import BaseModel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from typing import List
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from datetime import datetime
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from sqlalchemy.orm import Session
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from .model.database import Base, FinancialSummary, engine  # adjust path if needed

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Create tables if not exist (optional — do this once in dev)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Base.metadata.create_all(bind=engine)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class FinancialSummaryResponse(BaseModel):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: int
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                period: str
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    revenue: float
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expenses: float
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            profit: float
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                created_at: str  # or use datetime, but string is easier for frontend

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class Config:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from_att ributes = True  # for SQLAlchemy v2; for v1 use `orm_mode = True`

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Dependency to get DB session
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def get_db():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db = SessionLocal()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            yield db
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Add this line if you don't have SessionLocal yet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from sqlalchemy.orm import sessionmaker
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.get("/api/finance/summary", response_model=List[FinancialSummaryResponse])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def get_finance_summary(db: Session = Depends(get_db)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return db.query(FinancialSummary).order_by(FinancialSummary.created_at.desc()).all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # In backend/main.py — add at bottom
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # In main.py
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from routes import clients

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.include_router(clients.router)

# In backend/main.py — add at the bottom

from pydantic import BaseModel
from typing import List
from datetime import datetime
from sqlalchemy.orm import Session
from .model.database import AutomationAnalytics, engine

class AutomationAnalyticsResponse(BaseModel):
    id: int
    period: str
    revenue: float
    expenses: float
    profit: float
    project_completion: float
    team_utilization: float
    customer_satisfaction: float
    active_tasks: int
    ai_insight: str | None
    created_at: str

    class Config:
        from_attributes = True

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/api/analytics/automation", response_model=List[AutomationAnalyticsResponse])
def get_automation_analytics(db: Session = Depends(get_db)):
    return db.query(AutomationAnalytics).order_by(AutomationAnalytics.created_at.desc()).all()
    # In backend/main.py — add at bottom

    import pdfkit
    from fastapi.responses import FileResponse
    import os
    from datetime import datetime

    @app.get("/api/analytics/export-pdf")
    def export_analytics_pdf(db: Session = Depends(get_db)):
        # Fetch latest analytics
            records = db.query(AutomationAnalytics).order_by(AutomationAnalytics.created_at.desc()).limit(10).all()
                
                    # Build HTML content
                        html_content = f"""
                            <!DOCTYPE html>
                                <html>
                                    <head>
                                            <meta charset="utf-8">
                                                    <title>Automation Analytics Report</title>
                                                            <style>
                                                                        body {{ font-family: Arial, sans-serif; margin: 40px; }}
                                                                                    h1 {{ color: #1e293b; }}
                                                                                                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                                                                                                            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
                                                                                                                        th {{ background-color: #f8fafc; }}
                                                                                                                                    .metric {{ margin: 10px 0; }}
                                                                                                                                                .footer {{ margin-top: 40px; color: #64748b; font-size: 0.875rem; }}
                                                                                                                                                        </style>
                                                                                                                                                            </head>
                                                                                                                                                                <body>
                                                                                                                                                                        <h1>Automation Analytics Report</h1>
                                                                                                                                                                                <p>Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
                                                                                                                                                                                        
                                                                                                                                                                                                <div class="metrics">
                                                                                                                                                                                                            <div class="metric"><strong>Latest Period:</strong> {records[0].period if records else 'N/A'}</div>
                                                                                                                                                                                                                        <div class="metric"><strong>Revenue:</strong> ${records[0].revenue:,.2f} if records else 'N/A'</div>
                                                                                                                                                                                                                                    <div class="metric"><strong>Profit:</strong> ${records[0].profit:,.2f} if records else 'N/A'</div>
                                                                                                                                                                                                                                                <div class="metric"><strong>Project Completion:</strong> {records[0].project_completion:.2f}% if records else 'N/A'</div>
                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                <h2>Recent Records</h2>
                                                                                                                                                                                                                                                                        <table>
                                                                                                                                                                                                                                                                                    <thead>
                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                        <th>Period</th>
                                                                                                                                                                                                                                                                                                                                            <th>Revenue</th>
                                                                                                                                                                                                                                                                                                                                                                <th>Expenses</th>
                                                                                                                                                                                                                                                                                                                                                                                    <th>Profit</th>
                                                                                                                                                                                                                                                                                                                                                                                                        <th>Completion %</th>
                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {''.join(f"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>{r.period}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>${r.revenue:,.2f}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td>${r.expenses:,.2f}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td>${r.profit:,.2f}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>{r.project_completion:.2f}%</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """ for r in records)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </table>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Generated by AUTOPS-MVP Analytics Engine
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Save to temp file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        filename = f"analytics_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            filepath = f"/tmp/{filename}"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pdfkit.from_string(html_content, filepath)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return FileResponse(filepath, media_type='application/pdf', filename=filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")


