
import React, { useState, useEffect } from 'react';
import './AnalyticsReport.css';
import GoalCard from '../components/GoalCard'; // Reuse existing card
import ChartCard from '../components/ChartCard'; // We'll create this next
import AITip from '../components/AITip'; // New component for AI insights
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import './DatePickerOverride.css'; // 

const AnalyticsReport = () => {
  const [data, setData] = useState([]);
    const [loading, setLoading] = useState(true);
      const [error, setError] = useState(null);
        const [timeFilter, setTimeFilter] = useState('Weekly');
          const [tab, setTab] = useState('Finance');
          
 const [startDate, setStartDate] = useState(new Date());
          const [endDate, setEndDate] = useState(new Date());
          const handleExportPDF = async () => {
              try {
                  const response = await fetch('http://localhost:8000/api/analytics/export-pdf');
                      if (!response.ok) throw new Error('Failed to generate PDF');
                          
                              const blob = await response.blob();
                                  const url = window.URL.createObjectURL(blob);
                                      const a = document.createElement('a');
                                          a.href = url;
                                              a.download = 'automation-analytics-report.pdf';
                                                  document.body.appendChild(a);
                                                      a.click();
                                                          window.URL.revokeObjectURL(url);
                                                              document.body.removeChild(a);
                                                                } catch (err) {
                                                                    alert('Failed to export report: ' + err.message);
                                                                      }
                                                                      };
          }


            useEffect(() => {
                const fetchData = async () => {
                      try {
                              const response = await fetch('http://localhost:8000/api/analytics/automation');
                                      if (!response.ok) throw new Error('Network response was not ok');
                                              const result = await response.json();
                                                      setData(result);
                                                            } catch (err) {
                                                                    setError(err.message);
                                                                          } finally {
                                                                                  setLoading(false);
                                                                                        }
                                                                                            };

                                                                                                fetchData();
                                                                                                  }, []);

                                                                                                    if (loading) return <div className="analytics-loading">Loading analytics...</div>;
                                                                                                      if (error) return <div className="analytics-error">Error: {error}</div>;

                                                                                                        const latest = data[0] || {};

                                                                                                          return (
                                                                                                              <div className="analytics-report">
                                                                                                                    <header className="analytics-header">
                                                                                                                            <h1 className="analytics-title">Reports & Analytics</h1>
                                                                                                                                    <p className="analytics-subtitle">AI-Powered Insights</p>
                                                                                                                                          </header>
                                                                                                                                          // In render, replace the "Custom" button logic:
                                                                                                                                          {timeFilter === 'Custom' && (
                                                                                                                                            <div className="date-range-picker">
                                                                                                                                                <DatePicker
                                                                                                                                                      selected={startDate}
                                                                                                                                                            onChange={(date) => setStartDate(date)}
                                                                                                                                                                  selectsStart
                                                                                                                                                                        startDate={startDate}
                                                                                                                                                                              endDate={endDate}
                                                                                                                                                                                    placeholderText="Start Date"
                                                                                                                                                                                          className="date-input"
                                                                                                                                                                                              />
                                                                                                                                                                                                  <span className="date-separator">to</span>
                                                                                                                                                                                                      <DatePicker
                                                                                                                                                                                                            selected={endDate}
                                                                                                                                                                                                                  onChange={(date) => setEndDate(date)}
                                                                                                                                                                                                                        selectsEnd
                                                                                                                                                                                                                              startDate={startDate}
                                                                                                                                                                                                                                    endDate={endDate}
                                                                                                                                                                                                                                          minDate={startDate}
                                                                                                                                                                                                                                                placeholderText="End Date"
                                                                                                                                                                                                                                                      className="date-input"
                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                            ```

                                                                                                                                                {/* Time Filter */}
                                                                                                                                                      <div className="time-filter">
                                                                                                                                                              {['Daily', 'Weekly', 'Monthly', 'Custom'].map(filter => (
                                                                                                                                                                        <button
                                                                                                                                                                                    key={filter}
                                                                                                                                                                                                className={`filter-btn ${timeFilter === filter ? 'active' : ''}`}
                                                                                                                                                                                                            onClick={() => setTimeFilter(filter)}
                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                  {filter}
                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                          ```jsx
                                                                                                                                                                                                                                                          {/* Time Filter */}
                                                                                                                                                                                                                                                          <div className="time-filter">
                                                                                                                                                                                                                                                            {['Daily', 'Weekly', 'Monthly'].map(filter => (
                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                      key={filter}
                                                                                                                                                                                                                                                                            className={`filter-btn ${timeFilter === filter ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                  onClick={() => setTimeFilter(filter)}
                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                            {filter}
                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                        className={`filter-btn ${timeFilter === 'Custom' ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                            onClick={() => setTimeFilter('Custom')}
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                  Custom
                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                    {/* Custom Date Range (only when Custom is selected) */}
                                                                                                                                                                                                                                                                                                                    {timeFilter === 'Custom' && (
                                                                                                                                                                                                                                                                                                                      <div className="date-range-picker">
                                                                                                                                                                                                                                                                                                                          <DatePicker
                                                                                                                                                                                                                                                                                                                                selected={startDate}
                                                                                                                                                                                                                                                                                                                                      onChange={(date) => setStartDate(date)}
                                                                                                                                                                                                                                                                                                                                            selectsStart
                                                                                                                                                                                                                                                                                                                                                  startDate={startDate}
                                                                                                                                                                                                                                                                                                                                                        endDate={endDate}
                                                                                                                                                                                                                                                                                                                                                              placeholderText="Start Date"
                                                                                                                                                                                                                                                                                                                                                                    className="date-input"
                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                            <span className="date-separator">to</span>
                                                                                                                                                                                                                                                                                                                                                                                <DatePicker
                                                                                                                                                                                                                                                                                                                                                                                      selected={endDate}
                                                                                                                                                                                                                                                                                                                                                                                            onChange={(date) => setEndDate(date)}
                                                                                                                                                                                                                                                                                                                                                                                                  selectsEnd
                                                                                                                                                                                                                                                                                                                                                                                                        startDate={startDate}
                                                                                                                                                                                                                                                                                                                                                                                                              endDate={endDate}
                                                                                                                                                                                                                                                                                                                                                                                                                    minDate={startDate}
                                                                                                                                                                                                                                                                                                                                                                                                                          placeholderText="End Date"
                                                                                                                                                                                                                                                                                                                                                                                                                                className="date-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                      ```
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                          

                                                                                                                                                                                                                                                                {/* Metric Cards */}
                                                                                                                                                                                                                                                                      <div className="metric-cards">
                                                                                                                                                                                                                                                                              <GoalCard
                                                                                                                                                                                                                                                                                        title="Revenue"
                                                                                                                                                                                                                                                                                                  value={`$${latest.revenue?.toLocaleString() || '—'}`}
                                                                                                                                                                                                                                                                                                            subtitle={`${latest.revenue_trend || '+12.4%'} ↑`}
                                                                                                                                                                                                                                                                                                                      status="positive"
                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                      <GoalCard
                                                                                                                                                                                                                                                                                                                                                title="Expenses"
                                                                                                                                                                                                                                                                                                                                                          value={`$${latest.expenses?.toLocaleString() || '—'}`}
                                                                                                                                                                                                                                                                                                                                                                    subtitle={`${latest.expenses_trend || '-3.2%'} ↓`}
                                                                                                                                                                                                                                                                                                                                                                              status="negative"
                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                  {/* Tabs */}
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="tabs">
                                                                                                                                                                                                                                                                                                                                                                                                                {['Finance', 'Operations', 'Projects', 'Team'].map(t => (
                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                      key={t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`tab-btn ${tab === t ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setTab(t)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Filters */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="filters">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <select className="filter-select">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option>All Teams</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option>Engineering</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option>Sales</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option>Support</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select className="filter-select">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option>All Projects</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option>Project Alpha</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option>Project Beta</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="export-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>⬇</span> Export Report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Chart */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="chart-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="chart-title">Revenue Trend</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ChartCard data={data} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* KPI Grid */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="kpi-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <GoalCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title="Project Completion"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={`${latest.project_completion || '—'}%`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status="positive"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <GoalCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title="Team Utilization"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={`${latest.team_utilization || '—'}%`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status="warning"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <GoalCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title="Customer Satisfaction"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={`${latest.customer_satisfaction || '—'}/5`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              status="positive"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <GoalCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Active Tasks"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={`${latest.active_tasks || '—'}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status="info"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* AI Insights */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="ai-insights">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <AITip text={latest.ai_insight || "No AI insights available."} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="full-export-btn" onClick={handleExportPDF}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Export Full Report as PDF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default AnalyticsReport;