import { useEffect, useState } from 'react'
import './AutomationHub.css'
import Header from '../components/Header'
import AISuggestionCard from '../components/AISuggestionCard'
import WorkflowCard from '../components/WorkflowCard'
import ActivityItem from '../components/ActivityItem'
import BottomNav from '../components/BottomNav'

function AutomationHub() {
  const [aiSuggestions, setAiSuggestions] = useState([])
    const [workflows, setWorkflows] = useState([])
      const [activities, setActivities] = useState([])
        const [loading, setLoading] = useState(true)
          const [error, setError] = useState(null)

            useEffect(() => {
                fetchAutomationData()
                  }, [])

                    const fetchAutomationData = async () => {
                        try {
                              setError(null)
                                    
                                          // Fetch AI Suggestions
                                                const suggestionsRes = await fetch('http://localhost:8000/api/automation-hub/ai-suggestions')
                                                      const suggestionsData = await suggestionsRes.json()
                                                            setAiSuggestions(suggestionsData.suggestions || [])
                                                                  
                                                                        // Fetch Workflows
                                                                              const workflowsRes = await fetch('http://localhost:8000/api/automation-hub/workflows')
                                                                                    const workflowsData = await workflowsRes.json()
                                                                                          setWorkflows(workflowsData.workflows || [])
                                                                                                
                                                                                                      // Fetch Activity
                                                                                                            const activityRes = await fetch('http://localhost:8000/api/automation-hub/activity')
                                                                                                                  const activityData = await activityRes.json()
                                                                                                                        setActivities(activityData.activities || [])
                                                                                                                              
                                                                                                                                  } catch (error) {
                                                                                                                                        console.error('Error:', error)
                                                                                                                                              setError(error.message)
                                                                                                                                                  } finally {
                                                                                                                                                        setLoading(false)
                                                                                                                                                            }
                                                                                                                                                              }

                                                                                                                                                                const handleToggleWorkflow = async (workflowId, currentStatus) => {
                                                                                                                                                                    try {
                                                                                                                                                                          const response = await fetch(`http://localhost:8000/api/automation-hub/workflows/${workflowId}`, {
                                                                                                                                                                                  method: 'PATCH',
                                                                                                                                                                                          headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                  body: JSON.stringify({ is_active: !currentStatus })
                                                                                                                                                                                                        })
                                                                                                                                                                                                              
                                                                                                                                                                                                                    if (response.ok) {
                                                                                                                                                                                                                            // Refresh workflows
                                                                                                                                                                                                                                    fetchAutomationData()
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                    console.error('Error toggling workflow:', error)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                            const handleTrySuggestion = async (suggestionId) => {
                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                      const response = await fetch(
                                                                                                                                                                                                                                                                              `http://localhost:8000/api/automation-hub/ai-suggestions/${suggestionId}/implement`,
                                                                                                                                                                                                                                                                                      { method: 'POST' }
                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                        if (response.ok) {
                                                                                                                                                                                                                                                                                                                alert('AI Suggestion implemented! Creating workflow...')
                                                                                                                                                                                                                                                                                                                        fetchAutomationData()
                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                        console.error('Error implementing suggestion:', error)
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                if (loading) {
                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                          <div className="automation-hub-page">
                                                                                                                                                                                                                                                                                                                                                                  <Header username="Darmiyaan" title="Automation Hub" />
                                                                                                                                                                                                                                                                                                                                                                          <div className="loading">Loading Automation Hub...</div>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                            <div className="automation-hub-page">
                                                                                                                                                                                                                                                                                                                                                                                                  <Header username="Darmiyaan" title="Automation Hub" />
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="automation-hub-content">
                                                                                                                                                                                                                                                                                                                                                                                                                      {/* AI Suggestions Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                              <section className="ai-suggestions-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>AI Suggestions</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="suggestions-scroll">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {aiSuggestions.map(suggestion => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AISuggestionCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={suggestion.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      suggestion={suggestion}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onTryNow={() => handleTrySuggestion(suggestion.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Active Workflows Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <section className="workflows-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Active Workflows</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="workflows-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {workflows.map(workflow => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <WorkflowCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={workflow.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          workflow={workflow}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onToggle={() => handleToggleWorkflow(workflow.id, workflow.is_active)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Recent Activity Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="activity-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Recent Activity</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="activity-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {activities.map(activity => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ActivityItem key={activity.id} activity={activity} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <BottomNav currentPage="tech" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default AutomationHub