import React, { useState, useEffect } from 'react';
import './FinanceDashboard.css';
import FinanceCard from '../components/FinanceCard';

// Inside JSX:
<FinanceCard
  period="2026-Q1"
    revenue={150000}
      expenses={80000}
        profit={70000}
        />

const FinanceDashboard = () => {
  const [data, setData] = useState([]);
    const [loading, setLoading] = useState(true);
      const [error, setError] = useState(null);

        useEffect(() => {
            const fetchData = async () => {
                  try {
                          const response = await fetch('http://localhost:8000/api/finance/summary');
                                  if (!response.ok) throw new Error('Network response was not ok');
                                          const result = await response.json();
                                                  setData(result);
                                                        } catch (err) {
                                                                setError(err.message);
                                                                      } finally {
                                                                              setLoading(false);
                                                                                    }
                                                                                        };

                                                                                            fetchData();
                                                                                              }, []);

                                                                                                if (loading) return <div className="finance-loading">Loading finance data...</div>;
                                                                                                  if (error) return <div className="finance-error">Error: {error}</div>;

                                                                                                    return (
                                                                                                        <div className="finance-dashboard">
                                                                                                              <h1 className="finance-title">📊 Finance Dashboard</h1>

                                                                                                                    <div className="finance-cards">
                                                                                                                            {data.map((item) => (
                                                                                                                                      <div key={item.id} className="finance-card">
                                                                                                                                                  <h2 className="card-period">{item.period}</h2>
                                                                                                                                                              <div className="card-metrics">
                                                                                                                                                                            <div className="metric">
                                                                                                                                                                                            <span className="metric-label">Revenue:</span>
                                                                                                                                                                                                            <span className="metric-value metric-green">${item.revenue.toLocaleString()}</span>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                        <div className="metric">
                                                                                                                                                                                                                                                        <span className="metric-label">Expenses:</span>
                                                                                                                                                                                                                                                                        <span className="metric-value metric-red">${item.expenses.toLocaleString()}</span>
                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                    <div className="metric total">
                                                                                                                                                                                                                                                                                                                    <span className="metric-label">Profit:</span>
                                                                                                                                                                                                                                                                                                                                    <span className={`metric-value ${item.profit >= 0 ? 'metric-green' : 'metric-red'}`}>
                                                                                                                                                                                                                                                                                                                                                      ${item.profit.toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="finance-table-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="table-title">📈 Summary Table</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <table className="finance-table">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <th>Period</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Revenue</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <th>Expenses</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Profit</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th>Date</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {data.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr key={item.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>{item.period}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>${item.revenue.toLocaleString()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>${item.expenses.toLocaleString()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td className={item.profit >= 0 ? 'profit-positive' : 'profit-negative'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ${item.profit.toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td>{new Date(item.created_at).toLocaleDateString()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default FinanceDashboard;
