import { useEffect, useState } from 'react'
import './Operations.css'
import Header from '../components/Header'
import ProjectCard from '../components/ProjectCard'
import BottomNav from '../components/BottomNav'

function Operations() {
  const [operationsData, setOperationsData] = useState(null)
    const [loading, setLoading] = useState(true)
      const [error, setError] = useState(null)
        const [activeFilter, setActiveFilter] = useState('all')

          useEffect(() => {
              fetchOperationsData()
                }, [])

                  const fetchOperationsData = async () => {
                      try {
                            setError(null)
                                    const response = await fetch('/api/operations')
                                        
                                              if (!response.ok) {
                                                      throw new Error(`HTTP error! status: ${response.status}`)
                                                            }
                                                                  
                                                                        const contentType = response.headers.get("content-type")
                                                                              if (!contentType || !contentType.includes("application/json")) {
                                                                                      throw new Error("Response is not JSON! Check if backend is running correctly.")
                                                                                            }
                                                                                                  
                                                                                                        const data = await response.json()
                                                                                                              setOperationsData(data)
                                                                                                                  } catch (error) {
                                                                                                                        console.error('Error fetching operations data:', error)
                                                                                                                              setError(error.message)
                                                                                                                                  } finally {
                                                                                                                                        setLoading(false)
                                                                                                                                            }
                                                                                                                                              }

                                                                                                                                                if (loading) {
                                                                                                                                                    return (
                                                                                                                                                          <div className="operations-page">
                                                                                                                                                                  <Header username="Darmiyaan" title="Operations" />
                                                                                                                                                                          <div className="loading">Loading...</div>
                                                                                                                                                                                </div>
                                                                                                                                                                                    )
                                                                                                                                                                                      }

                                                                                                                                                                                        if (error) {
                                                                                                                                                                                            return (
                                                                                                                                                                                                  <div className="operations-page">
                                                                                                                                                                                                          <Header username="Darmiyaan" title="Operations" />
                                                                                                                                                                                                                  <div className="error-container">
                                                                                                                                                                                                                            <div className="error-message">
                                                                                                                                                                                                                                        <h3>⚠️ Connection Error</h3>
                                                                                                                                                                                                                                                    <p>{error}</p>
                                                                                                                                                                                                                                                                <button className="retry-btn" onClick={fetchOperationsData}>
                                                                                                                                                                                                                                                                              Retry
                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                    <BottomNav currentPage="operations" />
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                  if (!operationsData) {
                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                            <div className="operations-page">
                                                                                                                                                                                                                                                                                                                                                    <Header username="Darmiyaan" title="Operations" />
                                                                                                                                                                                                                                                                                                                                                            <div className="error-container">
                                                                                                                                                                                                                                                                                                                                                                      <p>No data available</p>
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                      <BottomNav currentPage="operations" />
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="operations-page">
                                                                                                                                                                                                                                                                                                                                                                                                              <Header username="Darmiyaan" title="Operations" />
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="operations-content">
                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Project Count */}
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="project-count">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="count-number">{operationsData.total_projects}</span> Active Projects
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Search Bar */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="search-bar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="search-icon">🔍</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" placeholder="Search projects..." />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Filter Tabs */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="filter-tabs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={activeFilter === 'all' ? 'active' : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setActiveFilter('all')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={activeFilter === 'team' ? 'active' : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setActiveFilter('team')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Team
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={activeFilter === 'priority' ? 'active' : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setActiveFilter('priority')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Priority
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Today Projects */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {operationsData.projects_today && operationsData.projects_today.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="projects-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="section-title">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Today <span className="count">({operationsData.projects_today.length})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {operationsData.projects_today.map(project => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ProjectCard key={project.id} project={project} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Upcoming Projects */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {operationsData.projects_upcoming && operationsData.projects_upcoming.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="projects-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="section-title">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Upcoming <span className="count">({operationsData.projects_upcoming.length})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {operationsData.projects_upcoming.map(project => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ProjectCard key={project.id} project={project} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Completed Projects */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {operationsData.projects_completed && operationsData.projects_completed.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="projects-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="section-title">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Completed <span className="count">({operationsData.projects_completed.length})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {operationsData.projects_completed.map(project => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ProjectCard key={project.id} project={project} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <BottomNav currentPage="operations" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Operations
