import { useEffect, useState } from 'react'
import './StrategyPlanning.css'
import Header from '../components/Header'
import GoalCard from '../components/GoalCard'

function StrategyPlanning() {
  const [stats, setStats] = useState(null)
    const [goals, setGoals] = useState([])
      const [forecast, setForecast] = useState(null)
        const [reviews, setReviews] = useState([])
          const [loading, setLoading] = useState(true)

            useEffect(() => {
                fetchAllData()
                  }, [])

                    const fetchAllData = async () => {
                        try {
                              // Fetch stats
                                    const statsRes = await fetch('http://localhost:8000/api/strategy-planning/stats')
                                          const statsData = await statsRes.json()
                                                setStats(statsData)

                                                      // Fetch goals
                                                            const goalsRes = await fetch('http://localhost:8000/api/strategy-planning/goals')
                                                                  const goalsData = await goalsRes.json()
                                                                        setGoals(goalsData.goals || [])

                                                                              // Fetch forecast
                                                                                    const forecastRes = await fetch('http://localhost:8000/api/strategy-planning/ai-forecast')
                                                                                          const forecastData = await forecastRes.json()
                                                                                                setForecast(forecastData)

                                                                                                      // Fetch reviews
                                                                                                            const reviewsRes = await fetch('http://localhost:8000/api/strategy-planning/upcoming-reviews')
                                                                                                                  const reviewsData = await reviewsRes.json()
                                                                                                                        setReviews(reviewsData.reviews || [])

                                                                                                                            } catch (error) {
                                                                                                                                  console.error('Error fetching data:', error)
                                                                                                                                      } finally {
                                                                                                                                            setLoading(false)
                                                                                                                                                }
                                                                                                                                                  }

                                                                                                                                                    const handleExportReport = async () => {
                                                                                                                                                        try {
                                                                                                                                                              const response = await fetch('http://localhost:8000/api/strategy-planning/export-report', {
                                                                                                                                                                      method: 'POST'
                                                                                                                                                                            })
                                                                                                                                                                                  const data = await response.json()
                                                                                                                                                                                        
                                                                                                                                                                                              if (data.success) {
                                                                                                                                                                                                      alert('Report exported successfully!')
                                                                                                                                                                                                              console.log('Report:', data.report)
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                              console.error('Error exporting report:', error)
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                      if (loading) return <div className="loading">Loading...</div>

                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                            <div className="strategy-planning-page">
                                                                                                                                                                                                                                                  <Header username="Darmiyaan" title="Strategy & Planning" hideBackButton={true} />

                                                                                                                                                                                                                                                        <div className="strategy-content">
                                                                                                                                                                                                                                                                {/* Stats Cards */}
                                                                                                                                                                                                                                                                        <div className="stats-grid">
                                                                                                                                                                                                                                                                                  <div className="stat-card blue">
                                                                                                                                                                                                                                                                                              <span className="stat-label">Active Goals</span>
                                                                                                                                                                                                                                                                                                          <span className="stat-value">{stats?.active_goals || 0}</span>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                              <div className="stat-card green">
                                                                                                                                                                                                                                                                                                                                          <span className="stat-label">On Track</span>
                                                                                                                                                                                                                                                                                                                                                      <span className="stat-value">{stats?.on_track || 0}</span>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                          <div className="stat-card orange">
                                                                                                                                                                                                                                                                                                                                                                                      <span className="stat-label">At Risk</span>
                                                                                                                                                                                                                                                                                                                                                                                                  <span className="stat-value">{stats?.at_risk || 0}</span>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Current Goals Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                    <section className="goals-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>Current Goals</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="goals-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {goals.map(goal => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <GoalCard key={goal.id} goal={goal} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* AI Goal Forecast Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {forecast && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <section className="forecast-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="forecast-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="forecast-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="forecast-icon">📊</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>AI Goal Forecast</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="forecast-text">{forecast.forecast_text}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="probability-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="probability-icon">📈</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="probability-label">Success Probability</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="probability-value">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {Math.round(forecast.success_probability * 100)}%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Upcoming Reviews Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="reviews-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Upcoming Reviews</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="reviews-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {reviews.map((review, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={index} className="review-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="review-date">{review.formatted_date}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="review-count">{review.goals_count} Goals</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Export Report Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="export-report-btn" onClick={handleExportReport}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="export-icon">📊</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Export Report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default StrategyPlanning