import { useEffect, useState } from 'react'
import './Templates.css'
import Header from '../components/Header'
import TemplateCard from '../components/TemplateCard'
import BottomNav from '../components/BottomNav'

function Templates() {
  const [templatesData, setTemplatesData] = useState(null)
    const [loading, setLoading] = useState(true)
      const [error, setError] = useState(null)
        const [activeCategory, setActiveCategory] = useState('All')
          const [searchQuery, setSearchQuery] = useState('')

            useEffect(() => {
                fetchTemplatesData()
                  }, [])

                    const fetchTemplatesData = async () => {
                        try {
                              setError(null)
                                    const response = await fetch('http://localhost:8000/api/templates')
                                          
                                                if (!response.ok) {
                                                        throw new Error(`HTTP error! status: ${response.status}`)
                                                              }
                                                                    
                                                                          const data = await response.json()
                                                                                setTemplatesData(data)
                                                                                    } catch (error) {
                                                                                          console.error('Error:', error)
                                                                                                setError(error.message)
                                                                                                    } finally {
                                                                                                          setLoading(false)
                                                                                                              }
                                                                                                                }

                                                                                                                  if (loading) {
                                                                                                                      return (
                                                                                                                            <div className="templates-page">
                                                                                                                                    <Header username="Darmiyaan" title="Automation Templates" />
                                                                                                                                            <div className="loading">Loading templates...</div>
                                                                                                                                                  </div>
                                                                                                                                                      )
                                                                                                                                                        }

                                                                                                                                                          if (error) {
                                                                                                                                                              return (
                                                                                                                                                                    <div className="templates-page">
                                                                                                                                                                            <Header username="Darmiyaan" title="Automation Templates" />
                                                                                                                                                                                    <div className="error-container">
                                                                                                                                                                                              <div className="error-message">
                                                                                                                                                                                                          <h3>⚠️ Connection Error</h3>
                                                                                                                                                                                                                      <p>{error}</p>
                                                                                                                                                                                                                                  <button className="retry-btn" onClick={fetchTemplatesData}>
                                                                                                                                                                                                                                                Retry
                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                      <BottomNav currentPage="tech" />
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                    // Filter templates by category and search
                                                                                                                                                                                                                                                                                                      const filteredTemplates = templatesData?.templates.filter(template => {
                                                                                                                                                                                                                                                                                                          const matchesCategory = activeCategory === 'All' || template.category === activeCategory
                                                                                                                                                                                                                                                                                                              const matchesSearch = template.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                                                                                                                                                                                                                                                                                                                                       template.description.toLowerCase().includes(searchQuery.toLowerCase())
                                                                                                                                                                                                                                                                                                                                           return matchesCategory && matchesSearch
                                                                                                                                                                                                                                                                                                                                             })

                                                                                                                                                                                                                                                                                                                                               return (
                                                                                                                                                                                                                                                                                                                                                   <div className="templates-page">
                                                                                                                                                                                                                                                                                                                                                         <Header username="Darmiyaan" title="Automation Templates" />
                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                     <div className="templates-content">
                                                                                                                                                                                                                                                                                                                                                                             {/* Page Title */}
                                                                                                                                                                                                                                                                                                                                                                                     <div className="page-header">
                                                                                                                                                                                                                                                                                                                                                                                               <h2>Automation Templates</h2>
                                                                                                                                                                                                                                                                                                                                                                                                         <p className="subtitle">Streamline your business workflows</p>
                                                                                                                                                                                                                                                                                                                                                                                                                 </div>

                                                                                                                                                                                                                                                                                                                                                                                                                         {/* Search Bar */}
                                                                                                                                                                                                                                                                                                                                                                                                                                 <div className="search-bar">
                                                                                                                                                                                                                                                                                                                                                                                                                                           <span className="search-icon">🔍</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                     <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 type="text" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             placeholder="Search templates..." 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         value={searchQuery}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     onChange={(e) => setSearchQuery(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {/* Category Filter Pills */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div className="category-pills">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {templatesData?.categories.map(category => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           key={category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         className={`category-pill ${activeCategory === category ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onClick={() => setActiveCategory(category)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {category === 'Salon & Beauty' && '💅 '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {category === 'Home Services' && '🏠 '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {/* Templates Grid */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div className="templates-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {filteredTemplates?.map(template => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <TemplateCard key={template.id} template={template} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {filteredTemplates?.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="no-results">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p>No templates found matching your search.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         export default Templates