from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os

# These match the settings we put in docker-compose.yml
# In Codespaces, the host is usually the service name 'db' or 'localhost'
POSTGRES_USER = os.getenv("DATABASE_USER", "postgres")
POSTGRES_PASSWORD = os.getenv("DATABASE_PASSWORD", "password_secret")
POSTGRES_DB = os.getenv("DATABASE_NAME", "mydatabase")
POSTGRES_SERVER = os.getenv("DATABASE_HOST", "db") 

# This is the connection string
SQLALCHEMY_DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}/{POSTGRES_DB}"

# Create the engine that communicates with the database
engine = create_engine(SQLALCHEMY_DATABASE_URL)

# Create a SessionLocal class for database sessions
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Base class for our database models
Base = declarative_base()
# In backend/model/database.py — add after Base = declarative_base()
# In backend/model/database.py — add after Base = declarative_base()

from sqlalchemy import Column, Integer, String, Numeric, DateTime, Text
from sqlalchemy.sql import func

class AutomationAnalytics(Base):
    __tablename__ = "automation_analytics"

        id = Column(Integer, primary_key=True, index=True)
            period = Column(String(10), nullable=False)  # e.g., "2026-W24"
                revenue = Column(Numeric(12,2), nullable=False)
                    expenses = Column(Numeric(12,2), nullable=False)
                        profit = Column(Numeric(12,2), nullable=False)
                            project_completion = Column(Numeric(5,2), nullable=False)  # 94.00%
                                team_utilization = Column(Numeric(5,2), nullable=False)   # 87.00%
                                    customer_satisfaction = Column(Numeric(3,2), nullable=False)  # 4.80
                                        active_tasks = Column(Integer, nullable=False)
                                            ai_insight = Column(Text, nullable=True)
                                                created_at = Column(DateTime(timezone=True), server_default=func.now())

from sqlalchemy import Column, Integer, String, Numeric, DateTime
from sqlalchemy.sql import func

class FinancialSummary(Base):
    __tablename__ = "financial_summary"

        id = Column(Integer, primary_key=True, index=True)
            period = Column(String(10), nullable=False)  # e.g., "2026-Q1"
                revenue = Column(Numeric(12, 2), nullable=False)
                    expenses = Column(Numeric(12, 2), nullable=False)
                        profit = Column(Numeric(12, 2), nullable=False)
                            created_at = Column(DateTime(timezone=True), server_default=func.now())

# Helper function to get a database session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
class Workflow(Base):
        __tablename__ = "workflows"
            
                id = Column(Integer, primary_key=True, index=True)
                    name = Column(String, index=True)
                        description = Column(String)
                            trigger = Column(String)  # "Invoice Overdue", "New Client", "Milestone Due"
                                action = Column(String)   # "Send Email", "Send Welcome Kit", "Team Notification"
                                    icon = Column(String)     # Emoji icon
                                        is_active = Column(Boolean, default=True)
                                            created_at = Column(DateTime, default=datetime.utcnow)
                                                
                                                    # Relationships
                                                        executions = relationship("WorkflowExecution", back_populates="workflow")

                                                        class WorkflowExecution(Base):
                                                            __tablename__ = "workflow_executions"
                                                                
                                                                    id = Column(Integer, primary_key=True, index=True)
                                                                        workflow_id = Column(Integer, ForeignKey("workflows.id"))
                                                                            status = Column(String)  # "success", "failed", "pending"
                                                                                executed_at = Column(DateTime, default=datetime.utcnow)
                                                                                    details = Column(String)
                                                                                        
                                                                                            # Relationship
                                                                                                workflow = relationship("Workflow", back_populates="executions")

                                                                                                class AISuggestion(Base):
                                                                                                    __tablename__ = "ai_suggestions"
                                                                                                        
                                                                                                            id = Column(Integer, primary_key=True, index=True)
                                                                                                                title = Column(String)
                                                                                                                    description = Column(String)
                                                                                                                        icon = Column(String)
                                                                                                                            category = Column(String)  # "client_onboarding", "reminders", "automation"
                                                                                                                                priority = Column(Integer)  # 1-5
                                                                                                                                    is_implemented = Column(Boolean, default=False)
                                                                                                                                        created_at = Column(DateTime, default=datetime.utcnow)

                                                                                                                                        class ActivityLog(Base):
                                                                                                                                            __tablename__ = "activity_logs"
                                                                                                                                                
                                                                                                                                                    id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                        icon = Column(String)
                                                                                                                                                            title = Column(String)
                                                                                                                                                                description = Column(String)
                                                                                                                                                                    category = Column(String)  # "workflow", "system", "ai"
                                                                                                                                                                        created_at = Column(DateTime, default=datetime.utcnow)
                                                                                                                                            class OnboardingFlow(Base):
                                                                                                                                                    __tablename__ = "onboarding_flows"
                                                                                                                                                        
                                                                                                                                                            id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                name = Column(String, index=True)
                                                                                                                                                                    trigger_type = Column(String)  # "post-booking", "manual", "scheduled"
                                                                                                                                                                        is_active = Column(Boolean, default=True)
                                                                                                                                                                            created_at = Column(DateTime, default=datetime.utcnow)
                                                                                                                                                                                
                                                                                                                                                                                    # Relationships
                                                                                                                                                                                        steps = relationship("OnboardingStep", back_populates="flow", order_by="OnboardingStep.order")
                                                                                                                                                                                            executions = relationship("OnboardingExecution", back_populates="flow")

                                                                                                                                                                                            class OnboardingStep(Base):
                                                                                                                                                                                                __tablename__ = "onboarding_steps"
                                                                                                                                                                                                    
                                                                                                                                                                                                        id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                            flow_id = Column(Integer, ForeignKey("onboarding_flows.id"))
                                                                                                                                                                                                                step_type = Column(String)  # "whatsapp_checklist", "location_link", "helpdesk_info", "id_scan"
                                                                                                                                                                                                                    order = Column(Integer)
                                                                                                                                                                                                                        config = Column(Text)  # JSON configuration
                                                                                                                                                                                                                            is_enabled = Column(Boolean, default=True)
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                    # Relationship
                                                                                                                                                                                                                                        flow = relationship("OnboardingFlow", back_populates="steps")

                                                                                                                                                                                                                                        class OnboardingExecution(Base):
                                                                                                                                                                                                                                            __tablename__ = "onboarding_executions"
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                        flow_id = Column(Integer, ForeignKey("onboarding_flows.id"))
                                                                                                                                                                                                                                                            customer_id = Column(Integer, ForeignKey("bookings.id"))  # Link to booking
                                                                                                                                                                                                                                                                status = Column(String)  # "in_progress", "completed", "failed"
                                                                                                                                                                                                                                                                    current_step = Column(Integer, default=0)
                                                                                                                                                                                                                                                                        started_at = Column(DateTime, default=datetime.utcnow)
                                                                                                                                                                                                                                                                            completed_at = Column(DateTime, nullable=True)
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    # Relationships
                                                                                                                                                                                                                                                                                        flow = relationship("OnboardingFlow", back_populates="executions")
                                                                                                                                                                                                                                                                                            customer = relationship("Booking")

                                                                                                                                                                                                                                                                                            class IDConfiguration(Base):
                                                                                                                                                                                                                                                                                                __tablename__ = "id_configurations"
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                            ocr_engine = Column(String, default="BlinkID")
                                                                                                                                                                                                                                                                                                                license_key_active = Column(Boolean, default=True)
                                                                                                                                                                                                                                                                                                                    field_mappings = Column(Text)  # JSON: {full_name: "customer_name", document_id: "gov_id_num"}
                                                                                                                                                                                                                                                                                                                        validation_rules = Column(Text)  # JSON: {validate_expiry: true, require_photo_match: true}
                                                                                                                                                                                                                                                                                                                            privacy_settings = Column(Text)  # JSON: {blur_sensitive_data: false, dont_store_images: true}
                                                                                                                                                                                                                                                                                                                                created_at = Column(DateTime, default=datetime.utcnow)

                                                                                                                                                                                                                                                                                                                                class LocationSettings(Base):
                                                                                                                                                                                                                                                                                                                                    __tablename__ = "location_settings"
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                            id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                google_map_link = Column(String)
                                                                                                                                                                                                                                                                                                                                                    use_dynamic_linking = Column(Boolean, default=False)
                                                                                                                                                                                                                                                                                                                                                        pre_arrival_trigger_enabled = Column(Boolean, default=True)
                                                                                                                                                                                                                                                                                                                                                            trigger_time_hours = Column(Integer, default=1)  # 1, 2, or 24 hours
                                                                                                                                                                                                                                                                                                                                                                helpdesk_phone = Column(String)
                                                                                                                                                                                                                                                                                                                                                                    notification_template = Column(Text)
                                                                                                                                                                                                                                                                                                                                                                        created_at = Column(DateTime, default=datetime.utcnow)

                                                                                                                                                                                                                                                                                                                                                                        class PreServiceChecklist(Base):
                                                                                                                                                                                                                                                                                                                                                                            __tablename__ = "pre_service_checklists"
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                        name = Column(String)
                                                                                                                                                                                                                                                                                                                                                                                            trigger_hours_before = Column(Integer, default=24)
                                                                                                                                                                                                                                                                                                                                                                                                intro_message = Column(Text)
                                                                                                                                                                                                                                                                                                                                                                                                    require_confirmation = Column(Boolean, default=True)
                                                                                                                                                                                                                                                                                                                                                                                                        remind_if_unread = Column(Boolean, default=False)
                                                                                                                                                                                                                                                                                                                                                                                                            created_at = Column(DateTime, default=datetime.utcnow)
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    # Relationships
                                                                                                                                                                                                                                                                                                                                                                                                                        items = relationship("ChecklistItem", back_populates="checklist")

                                                                                                                                                                                                                                                                                                                                                                                                                        class ChecklistItem(Base):
                                                                                                                                                                                                                                                                                                                                                                                                                            __tablename__ = "checklist_items"
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                    id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                        checklist_id = Column(Integer, ForeignKey("pre_service_checklists.id"))
                                                                                                                                                                                                                                                                                                                                                                                                                                            text = Column(String)
                                                                                                                                                                                                                                                                                                                                                                                                                                                order = Column(Integer)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Relationship
                                                                                                                                                                                                                                                                                                                                                                                                                                                            checklist = relationship("PreServiceChecklist", back_populates="items")
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                            class Goal(Base):
                                                                                                                                                                                                                                                                                                                                                                                                                                    __tablename__ = "goals"
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                title = Column(String, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    description = Column(String)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        status = Column(String)  # "on_track", "at_risk", "completed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            progress = Column(Float)  # 0.0 to 1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                target_date = Column(DateTime)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    owner_name = Column(String)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        owner_avatar = Column(String, nullable=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            created_at = Column(DateTime, default=datetime.utcnow)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class GoalReview(Base):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    __tablename__ = "goal_reviews"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                review_date = Column(DateTime)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    goals_count = Column(Integer)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        created_at = Column(DateTime, default=datetime.utcnow)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class AIForecast(Base):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            __tablename__ = "ai_forecasts"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        forecast_text = Column(Text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success_probability = Column(Float)  # 0.0 to 1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                generated_at = Column(DateTime, default=datetime.utcnow)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class Goal(Base):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    __tablename__ = "goals"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title = Column(String, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description = Column(String)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        status = Column(String)  # "on_track", "at_risk", "completed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            progress = Column(Float)  # 0.0 to 1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target_date = Column(DateTime)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    owner_name = Column(String)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        owner_avatar = Column(String, nullable=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            created_at = Column(DateTime, default=datetime.utcnow)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class GoalReview(Base):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    __tablename__ = "goal_reviews"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                review_date = Column(DateTime)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    goals_count = Column(Integer)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        created_at = Column(DateTime, default=datetime.utcnow)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class AIForecast(Base):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            __tablename__ = "ai_forecasts"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id = Column(Integer, primary_key=True, index=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        forecast_text = Column(Text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success_probability = Column(Float)  # 0.0 to 1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                generated_at = Column(DateTime, default=datetime.utcnow)