import openai
import os
from dotenv import load_dotenv
from datetime import datetime
import re

load_dotenv()

class OpenAIService:
    def __init__(self):
            self.api_key = os.getenv("OPENAI_API_KEY")
                    
                            if not self.api_key:
                                        raise ValueError("OpenAI API key not configured in .env file")
                                                
                                                        openai.api_key = self.api_key
                                                            
                                                                async def transcribe_audio(self, audio_file_path: str):
                                                                        """
                                                                                Transcribe audio file using OpenAI Whisper
                                                                                        Matches your "Real-Time Transcription" screen
                                                                                                """
                                                                                                        try:
                                                                                                                    with open(audio_file_path, "rb") as audio_file:
                                                                                                                                    transcript = openai.Audio.transcribe(
                                                                                                                                                        model="whisper-1",
                                                                                                                                                                            file=audio_file,
                                                                                                                                                                                                response_format="verbose_json"
                                                                                                                                                                                                                )
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                        "text": transcript.text,
                                                                                                                                                                                                                                                                        "confidence": transcript.segments[0].get('confidence', 0.0) if transcript.segments else 0.0,
                                                                                                                                                                                                                                                                                        "segments": transcript.segments
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                        raise Exception(f"Transcription error: {str(e)}")
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                async def detect_booking_intent(self, transcription_text: str):
                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                Use GPT-4 to detect booking intent and extract details
                                                                                                                                                                                                                                                                                                                                                        Matches your "Booking Clue Detection" screen with 96% confidence
                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                    response = openai.ChatCompletion.create(
                                                                                                                                                                                                                                                                                                                                                                                                    model="gpt-4",
                                                                                                                                                                                                                                                                                                                                                                                                                    messages=[
                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "role": "system",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "content": """You are an AI that detects booking intent from call transcriptions.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Extract the following information:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1. Intent: Does the customer want to book/schedule something? (yes/no)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2. Customer name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3. Phone number (if mentioned)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                4. Preferred date/time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                5. Service type
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                6. Confidence score (0-100%)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                7. Detected signals (keywords that indicate booking intent)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Respond in JSON format:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "intent_detected": true/false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "confidence": 96,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "customer_name": "Sarah Johnson",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "phone": "+1234567890",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "date": "2025-01-17T14:30:00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "service": "consultation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "detected_signals": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {"type": "intent", "text": "interested in scheduling", "confidence": 98, "timestamp": "00:18"},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"type": "date", "text": "Tuesday or Wednesday afternoon", "confidence": 95, "timestamp": "00:35"},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {"type": "time", "text": "between 2 and 4 PM", "confidence": 92, "timestamp": "00:35"},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"type": "confirmation", "text": "book me for Wednesday at 2:30 PM", "confidence": 99, "timestamp": "00:48"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "role": "user",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "content": f"Transcription: {transcription_text}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            temperature=0.3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                import json
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result = json.loads(response.choices[0].message.content)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return result
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise Exception(f"Intent detection error: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def detect_keywords(self, text: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Detect important keywords in transcription
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        For highlighting in your UI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        booking_keywords = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'book', 'booking', 'schedule', 'appointment', 'consultation',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'meeting', 'reserve', 'reservation', 'availability', 'available',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'calendar', 'confirm', 'confirmation'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    detected = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text_lower = text.lower()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for keyword in booking_keywords:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if keyword in text_lower:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        detected.append(keyword)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return detected