from twilio.rest import Client
import os
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

class WhatsAppService:
    def __init__(self):
            self.account_sid = os.getenv("TWILIO_ACCOUNT_SID")
                    self.auth_token = os.getenv("TWILIO_AUTH_TOKEN")
                            self.whatsapp_from = os.getenv("WHATSAPP_FROM", "whatsapp:+14155238886")  # Twilio Sandbox
                                    
                                            if not all([self.account_sid, self.auth_token]):
                                                        raise ValueError("Twilio credentials not configured")
                                                                
                                                                        self.client = Client(self.account_sid, self.auth_token)
                                                                            
                                                                                async def send_confirmation(self, to_number: str, customer_name: str, 
                                                                                                               booking_date: datetime, service_type: str, 
                                                                                                                                              calendar_link: str = None):
                                                                                                                                                      """
                                                                                                                                                              Send booking confirmation via WhatsApp
                                                                                                                                                                      Matches your "WhatsApp Messaging" screen template
                                                                                                                                                                              """
                                                                                                                                                                                      message_body = self.get_confirmation_preview(
                                                                                                                                                                                                  customer_name, booking_date, service_type, calendar_link
                                                                                                                                                                                                          )
                                                                                                                                                                                                                  
                                                                                                                                                                                                                          try:
                                                                                                                                                                                                                                      message = self.client.messages.create(
                                                                                                                                                                                                                                                      from_=self.whatsapp_from,
                                                                                                                                                                                                                                                                      to=f"whatsapp:{to_number}",
                                                                                                                                                                                                                                                                                      body=message_body
                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                              return message
                                                                                                                                                                                                                                                                                                                      except Exception as e:
                                                                                                                                                                                                                                                                                                                                  raise Exception(f"WhatsApp error: {str(e)}")
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                          def get_confirmation_preview(self, customer_name: str, booking_date: datetime, 
                                                                                                                                                                                                                                                                                                                                                                           service_type: str, calendar_link: str = None):
                                                                                                                                                                                                                                                                                                                                                                                   """
                                                                                                                                                                                                                                                                                                                                                                                           Generate confirmation message preview
                                                                                                                                                                                                                                                                                                                                                                                                   """
                                                                                                                                                                                                                                                                                                                                                                                                           formatted_date = booking_date.strftime("%A, %B %d at %I:%M %p")
                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                           message = f"""Hi {customer_name}! 👋

                                                                                                                                                                                                                                                                                                                                                                                                                           Your consultation has been confirmed for {formatted_date}.

                                                                                                                                                                                                                                                                                                                                                                                                                           📅 Add to calendar: {calendar_link or 'https://cal.link/abc123'}
                                                                                                                                                                                                                                                                                                                                                                                                                           📋 View our catalogue: https://catalogue.example.com

                                                                                                                                                                                                                                                                                                                                                                                                                           Looking forward to meeting you!

                                                                                                                                                                                                                                                                                                                                                                                                                           Best regards,
                                                                                                                                                                                                                                                                                                                                                                                                                           The Team"""
                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                           return message
                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                   async def send_24h_reminder(self, to_number: str, customer_name: str,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   booking_date: datetime, service_type: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Send 24-hour reminder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   formatted_date = booking_date.strftime("%A, %B %d")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           formatted_time = booking_date.strftime("%I:%M %p")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           message_body = f"""Hi {customer_name}! 👋

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Reminder: You have an appointment tomorrow at {formatted_time}.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           📅 {formatted_date} at {formatted_time}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           📍 [Location]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Click here to confirm your attendance"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       message = self.client.messages.create(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       from_=self.whatsapp_from,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       to=f"whatsapp:{to_number}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       body=message_body
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   raise Exception(f"WhatsApp error: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           async def send_2h_reminder(self, to_number: str, customer_name: str,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          booking_date: datetime, service_type: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Send 2-hour final reminder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          formatted_time = booking_date.strftime("%I:%M %p")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          message_body = f"""Your appointment is in 2 hours!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Today at {formatted_time}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [Location]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Click here to confirm your attendance"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      message = self.client.messages.create(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      from_=self.whatsapp_from,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to=f"whatsapp:{to_number}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body=message_body
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  raise Exception(f"WhatsApp error: {str(e)}")