import './ActivityFeed.css'

function ActivityFeed() {
  // Mock activity data - will be replaced with real API data
    const activities = [
        {
              id: 1,
                    icon: '📞',
                          title: 'Call Recording Started',
                                description: 'Sarah Johnson - Incoming call',
                                      time: '2 min ago',
                                            color: '#5B7FFF'
                                                },
                                                    {
                                                          id: 2,
                                                                icon: '📝',
                                                                      title: 'Transcription Completed',
                                                                            description: 'Call with Sarah Johnson transcribed',
                                                                                  time: '3 min ago',
                                                                                        color: '#9B59B6'
                                                                                            },
                                                                                                {
                                                                                                      id: 3,
                                                                                                            icon: '📅',
                                                                                                                  title: 'Booking Intent Detected',
                                                                                                                        description: '96% confidence - Auto-booking triggered',
                                                                                                                              time: '4 min ago',
                                                                                                                                    color: '#00D9A5'
                                                                                                                                        },
                                                                                                                                            {
                                                                                                                                                  id: 4,
                                                                                                                                                        icon: '✓',
                                                                                                                                                              title: 'Appointment Created',
                                                                                                                                                                    description: 'Wed, Jan 17 at 2:30 PM - Sarah Johnson',
                                                                                                                                                                          time: '5 min ago',
                                                                                                                                                                                color: '#4CAF50'
                                                                                                                                                                                    },
                                                                                                                                                                                        {
                                                                                                                                                                                              id: 5,
                                                                                                                                                                                                    icon: '💬',
                                                                                                                                                                                                          title: 'WhatsApp Sent',
                                                                                                                                                                                                                description: 'Confirmation message to Sarah Johnson',
                                                                                                                                                                                                                      time: '5 min ago',
                                                                                                                                                                                                                            color: '#25D366'
                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                          id: 6,
                                                                                                                                                                                                                                                icon: '🔔',
                                                                                                                                                                                                                                                      title: 'Reminders Scheduled',
                                                                                                                                                                                                                                                            description: '24-hour and 2-hour reminders set',
                                                                                                                                                                                                                                                                  time: '5 min ago',
                                                                                                                                                                                                                                                                        color: '#FFA500'
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                              ]

                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                    <div className="activity-feed">
                                                                                                                                                                                                                                                                                          <h3>Activity Feed</h3>
                                                                                                                                                                                                                                                                                                <p className="feed-subtitle">Real-time automation updates</p>

                                                                                                                                                                                                                                                                                                      <div className="activity-timeline">
                                                                                                                                                                                                                                                                                                              {activities.map(activity => (
                                                                                                                                                                                                                                                                                                                        <div key={activity.id} className="activity-item">
                                                                                                                                                                                                                                                                                                                                    <div 
                                                                                                                                                                                                                                                                                                                                                  className="activity-icon" 
                                                                                                                                                                                                                                                                                                                                                                style={{ backgroundColor: `${activity.color}20` }}
                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                          <span>{activity.icon}</span>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="activity-content">
                                                                                                                                                                                                                                                                                                                                                                                                                                <h4>{activity.title}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>{activity.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="activity-time">{activity.time}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default ActivityFeed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      




