function BookingDetection() {
      // Mock data - will be replaced with real API data
        const detectedSignals = [
            {
                  type: 'intent',
                        text: 'interested in scheduling',
                              confidence: 98,
                                    timestamp: '00:18'
                                        },
                                            {
                                                  type: 'date',
                                                        text: 'Tuesday or Wednesday afternoon',
                                                              confidence: 95,
                                                                    timestamp: '00:35'
                                                                        },
                                                                            {
                                                                                  type: 'time',
                                                                                        text: 'between 2 and 4 PM',
                                                                                              confidence: 92,
                                                                                                    timestamp: '00:35'
                                                                                                        },
                                                                                                            {
                                                                                                                  type: 'confirmation',
                                                                                                                        text: 'book me for Wednesday at 2:30 PM',
                                                                                                                              confidence: 99,
                                                                                                                                    timestamp: '00:48'
                                                                                                                                        }
                                                                                                                                          ]

                                                                                                                                            return (
                                                                                                                                                <div className="booking-detection">
                                                                                                                                                      <h2>Booking Clue Detection</h2>
                                                                                                                                                            <p className="subtitle">AI-powered intent recognition & signal extraction</p>

                                                                                                                                                                  <div className="confidence-banner">
                                                                                                                                                                          <div className="confidence-circle">
                                                                                                                                                                                    <div className="confidence-inner">
                                                                                                                                                                                                <span className="confidence-percent">96%</span>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                          <div className="confidence-info">
                                                                                                                                                                                                                                    <h3>Overall Booking Confidence</h3>
                                                                                                                                                                                                                                              <p>Booking Intent Detected</p>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                  <div className="detected-signals-section">
                                                                                                                                                                                                                                                                          <h3>Detected Signals</h3>
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                          {detectedSignals.map((signal, index) => (
                                                                                                                                                                                                                                                                                                    <div key={index} className="signal-card">
                                                                                                                                                                                                                                                                                                                <div className="signal-header">
                                                                                                                                                                                                                                                                                                                              <span className="signal-type">{signal.type}</span>
                                                                                                                                                                                                                                                                                                                                            <span className="signal-time">{signal.timestamp}</span>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                    <div className="signal-content">
                                                                                                                                                                                                                                                                                                                                                                                  <div className="signal-progress">
                                                                                                                                                                                                                                                                                                                                                                                                  <div 
                                                                                                                                                                                                                                                                                                                                                                                                                    className="signal-progress-bar" 
                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: `${signal.confidence}%` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="signal-details">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="signal-details">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="signal-text">"{signal.text}"</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="signal-confidence">{signal.confidence}%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="recommended-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>Recommended Actions</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <li>Auto-create calendar booking for Wednesday, 2:30 PM</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>Send WhatsApp confirmation with calendar link</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <li>Schedule 24-hour and 2-hour reminders</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="confirm-booking-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ✓ Confirm & Execute Actions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default BookingDetection
}