import './CallRecordingCard.css'

function CallRecordingCard({ call, detailed = false, onViewDetails }) {
  const getStatusColor = (status) => {
      switch(status) {
            case 'completed': return '#4CAF50'
                  case 'recording': return '#FFA500'
                        case 'failed': return '#FF6B6B'
                              default: return '#999'
                                  }
                                    }

                                      const getStatusText = (status) => {
                                          switch(status) {
                                                case 'completed': return 'Completed'
                                                      case 'recording': return 'Recording...'
                                                            case 'failed': return 'Failed'
                                                                  default: return status
                                                                      }
                                                                        }

                                                                          return (
                                                                              <div className="call-recording-card">
                                                                                    <div className="call-header">
                                                                                            <div className="call-info">
                                                                                                      <h4>Call #{call.id}</h4>
                                                                                                                {call.has_booking && (
                                                                                                                            <span className="booking-badge">Booking Detected</span>
                                                                                                                                      )}
                                                                                                                                              </div>
                                                                                                                                                      <span 
                                                                                                                                                                className="call-status" 
                                                                                                                                                                          style={{ color: getStatusColor(call.status) }}
                                                                                                                                                                                  >
                                                                                                                                                                                            {getStatusText(call.status)}
                                                                                                                                                                                                    </span>
                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                <div className="call-details">
                                                                                                                                                                                                                        <div className="detail-row">
                                                                                                                                                                                                                                  <span className="detail-label">Started:</span>
                                                                                                                                                                                                                                            <span className="detail-value">
                                                                                                                                                                                                                                                        {call.start_time ? new Date(call.start_time).toLocaleString() : 'N/A'}
                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                  <div className="detail-row">
                                                                                                                                                                                                                                                                                            <span className="detail-label">Duration:</span>
                                                                                                                                                                                                                                                                                                      <span className="detail-value">{call.duration || 'N/A'}</span>
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                      {call.has_transcription && (
                                                                                                                                                                                                                                                                                                                                <div className="detail-row">
                                                                                                                                                                                                                                                                                                                                            <span className="detail-label">Transcription:</span>
                                                                                                                                                                                                                                                                                                                                                        <span className="detail-value">✓ Available</span>
                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                      {onViewDetails && (
                                                                                                                                                                                                                                                                                                                                                                                              <button 
                                                                                                                                                                                                                                                                                                                                                                                                        className="view-details-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => onViewDetails(call.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                    View Details →
                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default CallRecordingCard