import { useState } from 'react'
import './DrawerMenu.css'

function DrawerMenu({ currentPage, onNavigate }) {
  const [isOpen, setIsOpen] = useState(false)

    const menuItems = [
        { id: 'automation-hub', icon: '🏠', label: 'Automation Hub' },
            { id: 'call-automation', icon: '📞', label: 'Call Automation' },
                { id: 'operations', icon: '📊', label: 'Operations' },
                    { id: 'strategy-planning', icon: '🎯', label: 'Strategy & Planning' },
                        { id: 'templates', icon: '📋', label: 'Templates' },
                            { id: 'id-config', icon: '🆔', label: 'ID Configuration' },
                                { id: 'workflow-setup', icon: '⚙️', label: 'Workflow Setup' },
                                    { id: 'configure-step', icon: '📝', label: 'Configure Step' },
                                        { id: 'onboarding-flow', icon: '🔄', label: 'Onboarding Flow' },
                                          ]

                                            const handleItemClick = (pageId) => {
                                                onNavigate(pageId)
                                                    setIsOpen(false)
                                                      }

                                                        return (
                                                            <>
                                                                  {/* Menu Button */}
                                                                        <button 
                                                                                className="drawer-menu-btn" 
                                                                                        onClick={() => setIsOpen(!isOpen)}
                                                                                                aria-label="Open menu"
                                                                                                      >
                                                                                                              ☰
                                                                                                                    </button>

                                                                                                                          {/* Overlay */}
                                                                                                                                {isOpen && (
                                                                                                                                        <div 
                                                                                                                                                  className="drawer-overlay" 
                                                                                                                                                            onClick={() => setIsOpen(false)}
                                                                                                                                                                    ></div>
                                                                                                                                                                          )}

                                                                                                                                                                                {/* Drawer */}
                                                                                                                                                                                      <div className={`drawer ${isOpen ? 'open' : ''}`}>
                                                                                                                                                                                              <div className="drawer-header">
                                                                                                                                                                                                        <h2>Menu</h2>
                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                              className="drawer-close-btn" 
                                                                                                                                                                                                                                          onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                ✕
                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                          <nav className="drawer-nav">
                                                                                                                                                                                                                                                                                                    {menuItems.map(item => (
                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                              key={item.id}
                                                                                                                                                                                                                                                                                                                                            className={`drawer-item ${currentPage === item.id ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                          onClick={() => handleItemClick(item.id)}
                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                    <span className="drawer-item-icon">{item.icon}</span>
                                                                                                                                                                                                                                                                                                                                                                                                  <span className="drawer-item-label">{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                {currentPage === item.id && (
                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="drawer-item-indicator"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="drawer-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="user-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="user-avatar">D</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="user-details">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="user-name">Darmiyaan</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="user-email">admin@company.com</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default DrawerMenu