import './GoalCard.css'

function GoalCard({ goal }) {
  const getStatusColor = (status) => {
      switch(status) {
            case 'on_track': return '#34C759'
                  case 'at_risk': return '#FF9500'
                        case 'completed': return '#8E8E93'
                              default: return '#8E8E93'
                                  }
                                    }

                                      const getStatusText = (status) => {
                                          switch(status) {
                                                case 'on_track': return 'On Track'
                                                      case 'at_risk': return 'At Risk'
                                                            case 'completed': return 'Completed'
                                                                  default: return status
                                                                      }
                                                                        }

                                                                          const getAvatarColor = (name) => {
                                                                              const colors = ['#5B7FFF', '#FF6B6B', '#00D9A5', '#FFA500', '#9B59B6']
                                                                                  const index = name.charCodeAt(0) % colors.length
                                                                                      return colors[index]
                                                                                        }

                                                                                          const progressPercent = Math.round(goal.progress * 100)
                                                                                            const targetDate = new Date(goal.target_date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })

                                                                                              return (
                                                                                                  <div className="goal-card">
                                                                                                        <div className="goal-header">
                                                                                                                <h3 className="goal-title">{goal.title}</h3>
                                                                                                                        <span 
                                                                                                                                  className="goal-status-badge"
                                                                                                                                            style={{ backgroundColor: `${getStatusColor(goal.status)}20`, color: getStatusColor(goal.status) }}
                                                                                                                                                    >
                                                                                                                                                              {getStatusText(goal.status)}
                                                                                                                                                                      </span>
                                                                                                                                                                            </div>

                                                                                                                                                                                  <p className="goal-description">{goal.description}</p>

                                                                                                                                                                                        <div className="goal-progress-section">
                                                                                                                                                                                                <div className="progress-header">
                                                                                                                                                                                                          <span className="progress-label">Progress</span>
                                                                                                                                                                                                                    <span className="progress-percent">{progressPercent}%</span>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                    <div className="progress-bar">
                                                                                                                                                                                                                                              <div 
                                                                                                                                                                                                                                                          className="progress-fill"
                                                                                                                                                                                                                                                                      style={{ 
                                                                                                                                                                                                                                                                                    width: `${progressPercent}%`,
                                                                                                                                                                                                                                                                                                  backgroundColor: getStatusColor(goal.status)
                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                        ></div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                            <div className="goal-footer">
                                                                                                                                                                                                                                                                                                                                                    <div className="goal-owner">
                                                                                                                                                                                                                                                                                                                                                              <div 
                                                                                                                                                                                                                                                                                                                                                                          className="owner-avatar"
                                                                                                                                                                                                                                                                                                                                                                                      style={{ backgroundColor: getAvatarColor(goal.owner_name) }}
                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                            {goal.owner_avatar || goal.owner_name.split(' ').map(n => n[0]).join('')}
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="owner-name">{goal.owner_name}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="goal-date">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="date-icon">📅</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="date-text">{targetDate}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default GoalCard