import './ProjectCard.css'

function ProjectCard({ project }) {
  const getStatusColor = (status) => {
      switch(status) {
            case 'On Track': return '#00D9A5'
                  case 'At Risk': return '#FFA500'
                        case 'Delayed': return '#FF6B6B'
                              case 'Completed': return '#999'
                                    default: return '#999'
                                        }
                                          }

                                            const getPriorityColor = (priority) => {
                                                switch(priority) {
                                                      case 'HIGH': return '#FF6B6B'
                                                            case 'MEDIUM': return '#FFA500'
                                                                  case 'LOW': return '#00D9A5'
                                                                        default: return '#999'
                                                                            }
                                                                              }

                                                                                const getStatusBorderColor = (status) => {
                                                                                    return getStatusColor(status)
                                                                                      }

                                                                                        return (
                                                                                            <div className="project-card" style={{ borderLeft: `4px solid ${getStatusBorderColor(project.status)}` }}>
                                                                                                  <div className="project-header">
                                                                                                          <div className="project-title-section">
                                                                                                                    <h4 className="project-title">{project.title}</h4>
                                                                                                                              <span 
                                                                                                                                          className="status-badge" 
                                                                                                                                                      style={{ backgroundColor: getStatusColor(project.status) }}
                                                                                                                                                                >
                                                                                                                                                                            {project.status}
                                                                                                                                                                                      </span>
                                                                                                                                                                                              </div>
                                                                                                                                                                                                      <button className="more-btn">⋯</button>
                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                  <div className="project-time">
                                                                                                                                                                                                                          {project.date} • {project.start_time} - {project.end_time}
                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                      <div className="project-footer">
                                                                                                                                                                                                                                              <div className="project-team">
                                                                                                                                                                                                                                                        {project.team.map(member => (
                                                                                                                                                                                                                                                                    <div 
                                                                                                                                                                                                                                                                                  key={member.id} 
                                                                                                                                                                                                                                                                                                className="team-avatar"
                                                                                                                                                                                                                                                                                                              style={{ backgroundColor: member.avatar_color }}
                                                                                                                                                                                                                                                                                                                            title={member.name}
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                      {member.name.charAt(0)}
                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                            <div className="project-badges">
                                                                                                                                                                                                                                                                                                                                                                                                      <span 
                                                                                                                                                                                                                                                                                                                                                                                                                  className="priority-badge"
                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                            color: getPriorityColor(project.priority),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderColor: getPriorityColor(project.priority)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {project.priority}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default ProjectCard
